# Generated by Django 5.1.3 on 2024-11-12 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='borrow_date',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardgame',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
