# Generated by Django 5.1.3 on 2024-11-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_remove_boardgame_borrow_date_boardgame_borrowed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
